title = "StoryWiki"

[[continuities]]
display_name = "Books"
reference_name = "books"
prefix = "b"

[[continuities]]
display_name = "TV & Movie"
reference_name = "tv_movie"
prefix = "e"

[[releases.books]]
display_name = "Book 1"
reference_name = "b1"
begins_group = "Original Trilogy"

[[releases.books]]
display_name = "Book 2"
reference_name = "b2"

[[releases.books]]
display_name = "Book 3"
reference_name = "b3"

[[releases.books]]
display_name = "Book 4"
reference_name = "b4"
begins_group = "Second Trilogy"

[[releases.tv_movie]]
display_name = "Episode 1"
reference_name = "e1"
begins_group = "Season 1"

[[releases.tv_movie]]
display_name = "Episode 2"
reference_name = "e2"

[[releases.tv_movie]]
display_name = "Episode 3"
reference_name = "e3"

[[releases.tv_movie]]
display_name = "Episode 4"
reference_name = "e4"

[[releases.tv_movie]]
display_name = "Episode 5"
reference_name = "e5"

[[releases.tv_movie]]
display_name = "Episode 6"
reference_name = "e6"

[[releases.tv_movie]]
display_name = "Movie"
reference_name = "em"
begins_group = ""


[[pages.books]]
display_name = "Index"
page_url = "index"
resource_path = "site-content/books/index.md"
categories = ["Meta"]

[[pages.tv_movie]]
display_name = "Index"
page_url = "index"
resource_path = "site-content/tv_movie/index.md"
categories = ["Meta"]

[[pages.books]]
display_name = "Johan"
page_url = "johan"
resource_path = "site-content/books/johan.md"
title_peers = ["john"]
categories = ["Characters"]

[[pages.tv_movie]]
display_name = "John"
page_url = "john"
resource_path = "site-content/tv_movie/john.md"
title_peers = ["johan"]
categories = ["Characters"]


[[pages.books]]
display_name = "Palace"
page_url = "palace"
resource_path = "site-content/books/palace.md"
categories = ["Locations"]

[[pages.tv_movie]]
display_name = "Palace"
page_url = "palace"
resource_path = "site-content/tv_movie/palace.md"
categories = ["Locations"]

[[pages.books]]
display_name = "The War"
page_url = "war"
resource_path = "site-content/books/war.md"
show_cond = ["o-b3"]
categories = ["Events"]